[package]
name = "holoscribe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
obj = "0.10.2"
regex = "1"
svg = "0.13.0"
thiserror = "1.0.38"

